{
    "message": null,
    "data": [
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/23. sách  tâm lý- gi_1530209243790.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "79czUotE",
            "name": "Kiến thức - kỹ năng",
            "description": "Các loại sách Kiến thức - kỹ năng",
            "parentCategoryId": "1rTZSyCQ",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "1rTZSyCQ",
              "name": "Sách - truyện thiếu nhi",
              "description": "Các loại sách - truyện thiếu nhi",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "GaIzUYsV",
            "name": "Truyện đọc",
            "description": "Các loại sách Truyện đọc",
            "parentCategoryId": "1rTZSyCQ",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "1rTZSyCQ",
              "name": "Sách - truyện thiếu nhi",
              "description": "Các loại sách - truyện thiếu nhi",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "l9FbTAf0",
            "name": "Truyện tranh",
            "description": "Các loại sách Truyện tranh",
            "parentCategoryId": "1rTZSyCQ",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "1rTZSyCQ",
              "name": "Sách - truyện thiếu nhi",
              "description": "Các loại sách - truyện thiếu nhi",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=1rTZSyCQ",
        "id": "1rTZSyCQ",
        "name": "Sách - truyện thiếu nhi",
        "description": "Các loại sách - truyện thiếu nhi",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=29CqHMh4",
        "id": "29CqHMh4",
        "name": "Dinh dưỡng - sức khoẻ cho bé",
        "description": "Các loại sách Dinh dưỡng - sức khoẻ cho bé",
        "parentCategoryId": "eaIau7HB",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "eaIau7HB",
          "name": "Sách nuôi dạy con",
          "description": "Các loại sách nuôi dạy con",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=30cBuVh4",
        "id": "30cBuVh4",
        "name": "Thơ - Kịch",
        "description": "Các loại sách Thơ - Kịch",
        "parentCategoryId": "zytBS6fk",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "zytBS6fk",
          "name": "Văn học nước ngoài",
          "description": "Các loại sách Văn học nước ngoài",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/21. tạp chí_1530209220620.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "",
            "bookCount": 3,
            "subCategories": [],
            "urlCategory": null,
            "id": "y9cqTpul",
            "name": "Tư duy - Kỹ năng sống",
            "description": "Các loại sách Tư duy - Kỹ năng sống",
            "parentCategoryId": "4EF6uqUM",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "4EF6uqUM",
              "name": "Sách kỹ năng - sống đẹp",
              "description": "Các loại sách kỹ năng - sống đẹp",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "yOs2SNHB",
            "name": "Tâm lý - sống đẹp",
            "description": "Các loại sách Tâm lý - sống đẹp",
            "parentCategoryId": "4EF6uqUM",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "4EF6uqUM",
              "name": "Sách kỹ năng - sống đẹp",
              "description": "Các loại sách kỹ năng - sống đẹp",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=4EF6uqUM",
        "id": "4EF6uqUM",
        "name": "Sách kỹ năng - sống đẹp",
        "description": "Các loại sách kỹ năng - sống đẹp",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/sách kỹ năng sống_1529581173346.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=4vIRcBF2",
        "id": "4vIRcBF2",
        "name": "Doanh nhân",
        "description": "Các loại sách Doanh nhân",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/8. từ điển_1530208906371.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=4wcwUjCl",
        "id": "4wcwUjCl",
        "name": "Quản trị nguồn nhân lực",
        "description": "Các loại sách Quản trị nguồn nhân lực",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/12. sách lịch sử_1530209100619.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "JghKtKUy",
            "name": "Nhịp cầu đầu tư",
            "description": "Các loại sách Nhịp cầu đầu tư",
            "parentCategoryId": "56HQuvhX",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "56HQuvhX",
              "name": "Tạp chí",
              "description": "Các loại sách Tạp chí",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "XRSRtJIp",
            "name": "Forbes",
            "description": "Các loại sách Forbes",
            "parentCategoryId": "56HQuvhX",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "56HQuvhX",
              "name": "Tạp chí",
              "description": "Các loại sách Tạp chí",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=56HQuvhX",
        "id": "56HQuvhX",
        "name": "Tạp chí",
        "description": "Các loại sách Tạp chí",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://cafe-pos-files.thebooks.vn/Image/17. sách chính trị_p_1533704357074.jpg",
        "bookCount": 3,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=66sjfDto",
        "id": "66sjfDto",
        "name": "Khác",
        "description": "Các loại danh mục khác",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=79czUotE",
        "id": "79czUotE",
        "name": "Kiến thức - kỹ năng",
        "description": "Các loại sách Kiến thức - kỹ năng",
        "parentCategoryId": "1rTZSyCQ",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "1rTZSyCQ",
          "name": "Sách - truyện thiếu nhi",
          "description": "Các loại sách - truyện thiếu nhi",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/20. sách y học_1530209208919.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "A0tOC5Tx",
            "name": "Lịch sử thế giới",
            "description": "Các loại sách Lịch sử thế giới",
            "parentCategoryId": "7GTGHdsD",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "7GTGHdsD",
              "name": "Sách lịch sử",
              "description": "Các loại sách lịch sử",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "x2snTQub",
            "name": "Lịch sử Việt Nam",
            "description": "Các loại sách Lịch sử Việt Nam",
            "parentCategoryId": "7GTGHdsD",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "7GTGHdsD",
              "name": "Sách lịch sử",
              "description": "Các loại sách lịch sử",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=7GTGHdsD",
        "id": "7GTGHdsD",
        "name": "Sách lịch sử",
        "description": "Các loại sách lịch sử",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=8ec5ClIV",
        "id": "8ec5ClIV",
        "name": "Chính trị",
        "description": "Các loại sách Chính trị",
        "parentCategoryId": "w7FPuBSm",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "w7FPuBSm",
          "name": "Sách kiến thức tổng hợp",
          "description": "Các loại sách kiến thức tổng hợp",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=9PsJiPc2",
        "id": "9PsJiPc2",
        "name": "Tôn giáo - Triết học",
        "description": "Các loại sách Tôn giáo - Triết học",
        "parentCategoryId": "w7FPuBSm",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "w7FPuBSm",
          "name": "Sách kiến thức tổng hợp",
          "description": "Các loại sách kiến thức tổng hợp",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=9XTBuQcD",
        "id": "9XTBuQcD",
        "name": "Văn học",
        "description": "Các loại sách Văn học",
        "parentCategoryId": "OJhwSVT9",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OJhwSVT9",
          "name": "Sách Tiếng Anh",
          "description": "Các loại sách Tiếng Anh",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=A0tOC5Tx",
        "id": "A0tOC5Tx",
        "name": "Lịch sử thế giới",
        "description": "Các loại sách Lịch sử thế giới",
        "parentCategoryId": "7GTGHdsD",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "7GTGHdsD",
          "name": "Sách lịch sử",
          "description": "Các loại sách lịch sử",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/13. sách khoa học- k_1530209114437.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=A3TqF4SM",
        "id": "A3TqF4SM",
        "name": "Truyện ngắn - Tản văn",
        "description": "Các loại sách Truyện ngắn - Tản vănt",
        "parentCategoryId": "LqFetlSG",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "LqFetlSG",
          "name": "Văn học Việt Nam",
          "description": "Các loại sách Văn học Việt Nam",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/15. sách tôn giáo- t_1530209146790.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=aaSPCxuW",
        "id": "aaSPCxuW",
        "name": "Tự truyện- Hồi ký - Nhân vật",
        "description": "Các loại sách Tự truyện- Hồi ký - Nhân vật",
        "parentCategoryId": "LqFetlSG",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "LqFetlSG",
          "name": "Văn học Việt Nam",
          "description": "Các loại sách Văn học Việt Nam",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=ADckFYhn",
        "id": "ADckFYhn",
        "name": "Lần đầu làm mẹ",
        "description": "Các loại sách Lần đầu làm mẹ",
        "parentCategoryId": "eaIau7HB",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "eaIau7HB",
          "name": "Sách nuôi dạy con",
          "description": "Các loại sách nuôi dạy con",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/19. sách công nghệ_t_1530209194449.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=ALt6iVSE",
        "id": "ALt6iVSE",
        "name": "Kiếm hiệp",
        "description": "Các loại sách Kiếm hiệp",
        "parentCategoryId": "zytBS6fk",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "zytBS6fk",
          "name": "Văn học nước ngoài",
          "description": "Các loại sách Văn học nước ngoài",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=aRSQipTp",
        "id": "aRSQipTp",
        "name": "Kỹ năng nuôi dạy con",
        "description": "Các loại sách Kỹ năng nuôi dạy con",
        "parentCategoryId": "eaIau7HB",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "eaIau7HB",
          "name": "Sách nuôi dạy con",
          "description": "Các loại sách nuôi dạy con",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=BDFeuJIY",
        "id": "BDFeuJIY",
        "name": "Truyện đọc thiếu nhi",
        "description": "Các loại sách Truyện đọc thiếu nhi",
        "parentCategoryId": "OJhwSVT9",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OJhwSVT9",
          "name": "Sách Tiếng Anh",
          "description": "Các loại sách Tiếng Anh",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=bJhoHyT1",
        "id": "bJhoHyT1",
        "name": "Truyện tranh",
        "description": "Các loại sách Truyện tranh",
        "parentCategoryId": "OJhwSVT9",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OJhwSVT9",
          "name": "Sách Tiếng Anh",
          "description": "Các loại sách Tiếng Anh",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/15. sách tôn giáo- t_1530209146790.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=BrF8uQfO",
        "id": "BrF8uQfO",
        "name": "Tự truyện- Hồi ký - Nhân vật",
        "description": "Các loại sách Tự truyện- Hồi ký - Nhân vật",
        "parentCategoryId": "zytBS6fk",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "zytBS6fk",
          "name": "Văn học nước ngoài",
          "description": "Các loại sách Văn học nước ngoài",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/16. sách văn hoá- du_1530209157749.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "29CqHMh4",
            "name": "Dinh dưỡng - sức khoẻ cho bé",
            "description": "Các loại sách Dinh dưỡng - sức khoẻ cho bé",
            "parentCategoryId": "eaIau7HB",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "eaIau7HB",
              "name": "Sách nuôi dạy con",
              "description": "Các loại sách nuôi dạy con",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "ADckFYhn",
            "name": "Lần đầu làm mẹ",
            "description": "Các loại sách Lần đầu làm mẹ",
            "parentCategoryId": "eaIau7HB",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "eaIau7HB",
              "name": "Sách nuôi dạy con",
              "description": "Các loại sách nuôi dạy con",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "aRSQipTp",
            "name": "Kỹ năng nuôi dạy con",
            "description": "Các loại sách Kỹ năng nuôi dạy con",
            "parentCategoryId": "eaIau7HB",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "eaIau7HB",
              "name": "Sách nuôi dạy con",
              "description": "Các loại sách nuôi dạy con",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=eaIau7HB",
        "id": "eaIau7HB",
        "name": "Sách nuôi dạy con",
        "description": "Các loại sách nuôi dạy con",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=GaIzUYsV",
        "id": "GaIzUYsV",
        "name": "Truyện đọc",
        "description": "Các loại sách Truyện đọc",
        "parentCategoryId": "1rTZSyCQ",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "1rTZSyCQ",
          "name": "Sách - truyện thiếu nhi",
          "description": "Các loại sách - truyện thiếu nhi",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=GbIycoHv",
        "id": "GbIycoHv",
        "name": "Tiểu thuyết",
        "description": "Các loại sách Tiểu thuyết",
        "parentCategoryId": "LqFetlSG",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "LqFetlSG",
          "name": "Văn học Việt Nam",
          "description": "Các loại sách Văn học Việt Nam",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=JghKtKUy",
        "id": "JghKtKUy",
        "name": "Nhịp cầu đầu tư",
        "description": "Các loại sách Nhịp cầu đầu tư",
        "parentCategoryId": "56HQuvhX",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "56HQuvhX",
          "name": "Tạp chí",
          "description": "Các loại sách Tạp chí",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=JosMumUd",
        "id": "JosMumUd",
        "name": "Ẩm thực - Làm đẹp",
        "description": "Các loại sách Ẩm thực - Làm đẹp",
        "parentCategoryId": "w7FPuBSm",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "w7FPuBSm",
          "name": "Sách kiến thức tổng hợp",
          "description": "Các loại sách kiến thức tổng hợp",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://cafe-pos-files.thebooks.vn/Image/21. tạp chí_1533703588836.jpg",
        "bookCount": 5,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=KXsRt9ub",
        "id": "KXsRt9ub",
        "name": "Information Technology",
        "description": "Cho dân IT",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-25T06:59:40.025Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=l9FbTAf0",
        "id": "l9FbTAf0",
        "name": "Truyện tranh",
        "description": "Các loại sách Truyện tranh",
        "parentCategoryId": "1rTZSyCQ",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "1rTZSyCQ",
          "name": "Sách - truyện thiếu nhi",
          "description": "Các loại sách - truyện thiếu nhi",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=ljh2HAuA",
        "id": "ljh2HAuA",
        "name": "Tiểu thuyết",
        "description": "Các loại sách Tiểu thuyết",
        "parentCategoryId": "zytBS6fk",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "zytBS6fk",
          "name": "Văn học nước ngoài",
          "description": "Các loại sách Văn học nước ngoài",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/11. sách kiến thức t_1530208944768.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/13. sách khoa học- k_1530209114437.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "A3TqF4SM",
            "name": "Truyện ngắn - Tản văn",
            "description": "Các loại sách Truyện ngắn - Tản vănt",
            "parentCategoryId": "LqFetlSG",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "LqFetlSG",
              "name": "Văn học Việt Nam",
              "description": "Các loại sách Văn học Việt Nam",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/15. sách tôn giáo- t_1530209146790.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "aaSPCxuW",
            "name": "Tự truyện- Hồi ký - Nhân vật",
            "description": "Các loại sách Tự truyện- Hồi ký - Nhân vật",
            "parentCategoryId": "LqFetlSG",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "LqFetlSG",
              "name": "Văn học Việt Nam",
              "description": "Các loại sách Văn học Việt Nam",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "GbIycoHv",
            "name": "Tiểu thuyết",
            "description": "Các loại sách Tiểu thuyết",
            "parentCategoryId": "LqFetlSG",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "LqFetlSG",
              "name": "Văn học Việt Nam",
              "description": "Các loại sách Văn học Việt Nam",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "WNt5cnuw",
            "name": "Du ký - Phóng sự - Ký sự",
            "description": "Các loại sách Du ký - Phóng sự - Ký sự",
            "parentCategoryId": "LqFetlSG",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "LqFetlSG",
              "name": "Văn học Việt Nam",
              "description": "Các loại sách Văn học Việt Nam",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "zKIkuDhQ",
            "name": "Thơ - Ca dao - Kịch",
            "description": "Các loại sách Thơ - Ca dao - Kịch",
            "parentCategoryId": "LqFetlSG",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "LqFetlSG",
              "name": "Văn học Việt Nam",
              "description": "Các loại sách Văn học Việt Nam",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=LqFetlSG",
        "id": "LqFetlSG",
        "name": "Văn học Việt Nam",
        "description": "Các loại sách Văn học Việt Nam",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=mzI2f0Fj",
        "id": "mzI2f0Fj",
        "name": "Khoa học phổ thông",
        "description": "Các loại sách Khoa học phổ thông",
        "parentCategoryId": "OJhwSVT9",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OJhwSVT9",
          "name": "Sách Tiếng Anh",
          "description": "Các loại sách Tiếng Anh",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/7. sách học ngoại ng_1530208876609.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=NjI5sku2",
        "id": "NjI5sku2",
        "name": "Kỹ năng làm việc",
        "description": "Các loại sách Kỹ năng làm việc",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/10. giáo trình đh_cđ_1530208930436.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=NpuGIkFA",
        "id": "NpuGIkFA",
        "name": "Kinh tế học",
        "description": "Các loại sách Kinh tế học",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/14. sách điện ảnh_ n_1530209133226.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "9XTBuQcD",
            "name": "Văn học",
            "description": "Các loại sách Văn học",
            "parentCategoryId": "OJhwSVT9",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OJhwSVT9",
              "name": "Sách Tiếng Anh",
              "description": "Các loại sách Tiếng Anh",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "BDFeuJIY",
            "name": "Truyện đọc thiếu nhi",
            "description": "Các loại sách Truyện đọc thiếu nhi",
            "parentCategoryId": "OJhwSVT9",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OJhwSVT9",
              "name": "Sách Tiếng Anh",
              "description": "Các loại sách Tiếng Anh",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "bJhoHyT1",
            "name": "Truyện tranh",
            "description": "Các loại sách Truyện tranh",
            "parentCategoryId": "OJhwSVT9",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OJhwSVT9",
              "name": "Sách Tiếng Anh",
              "description": "Các loại sách Tiếng Anh",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "mzI2f0Fj",
            "name": "Khoa học phổ thông",
            "description": "Các loại sách Khoa học phổ thông",
            "parentCategoryId": "OJhwSVT9",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OJhwSVT9",
              "name": "Sách Tiếng Anh",
              "description": "Các loại sách Tiếng Anh",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "y2hqujUL",
            "name": "Kinh tế",
            "description": "Các loại sách Kinh tế",
            "parentCategoryId": "OJhwSVT9",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OJhwSVT9",
              "name": "Sách Tiếng Anh",
              "description": "Các loại sách Tiếng Anh",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=OJhwSVT9",
        "id": "OJhwSVT9",
        "name": "Sách Tiếng Anh",
        "description": "Các loại sách Tiếng Anh",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/sách kinh tế_1529581083985.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/sách kỹ năng sống_1529581173346.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "4vIRcBF2",
            "name": "Doanh nhân",
            "description": "Các loại sách Doanh nhân",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/8. từ điển_1530208906371.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "4wcwUjCl",
            "name": "Quản trị nguồn nhân lực",
            "description": "Các loại sách Quản trị nguồn nhân lực",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/7. sách học ngoại ng_1530208876609.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "NjI5sku2",
            "name": "Kỹ năng làm việc",
            "description": "Các loại sách Kỹ năng làm việc",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/10. giáo trình đh_cđ_1530208930436.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "NpuGIkFA",
            "name": "Kinh tế học",
            "description": "Các loại sách Kinh tế học",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/1. sách văn học_1530208826143.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "rBubF0cp",
            "name": "Marketing - Bán hàng",
            "description": "Các loại sách Marketing - Bán hàng",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/sách tham khảo_1529581210847.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "WehPUxu1",
            "name": "Quản trị - Lãnh đạo",
            "description": "Các loại sách Quản trị - Lãnh đạo",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/9. truyện tranh_1530208917912.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "XviKFrIE",
            "name": "Tài chính - Kế toán - Đầu tư",
            "description": "Các loại sách Tài chính - Kế toán - Đầu tư",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/sách thiếu nhi_1529581149475.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "YDcbIyCA",
            "name": "PR - Truyền thông",
            "description": "Các loại sách PR - Truyền thông",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/5. sách bà mẹ & em b_1530208859712.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "yeU9I7u9",
            "name": "Khởi nghiệp",
            "description": "Các loại sách Khởi nghiệp",
            "parentCategoryId": "OVuEcBfb",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "OVuEcBfb",
              "name": "Sách kinh tế",
              "description": "Các loại sách kinh tế",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=OVuEcBfb",
        "id": "OVuEcBfb",
        "name": "Sách kinh tế",
        "description": "Các loại sách kinh tế",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=PGcjfQTm",
        "id": "PGcjfQTm",
        "name": "Sức khoẻ - Y học - Dinh dưỡng",
        "description": "Các loại sách Sức khoẻ - Y học - Dinh dưỡng",
        "parentCategoryId": "w7FPuBSm",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "w7FPuBSm",
          "name": "Sách kiến thức tổng hợp",
          "description": "Các loại sách kiến thức tổng hợp",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=pMHdteck",
        "id": "pMHdteck",
        "name": "Địa lý",
        "description": "Các loại sách Địa lý",
        "parentCategoryId": "w7FPuBSm",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "w7FPuBSm",
          "name": "Sách kiến thức tổng hợp",
          "description": "Các loại sách kiến thức tổng hợp",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/1. sách văn học_1530208826143.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=rBubF0cp",
        "id": "rBubF0cp",
        "name": "Marketing - Bán hàng",
        "description": "Các loại sách Marketing - Bán hàng",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/13. sách khoa học- k_1530209114437.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=ReCKUNu0",
        "id": "ReCKUNu0",
        "name": "Truyện ngắn - Tản văn",
        "description": "Các loại sách Truyện ngắn - Tản vănt",
        "parentCategoryId": "zytBS6fk",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "zytBS6fk",
          "name": "Văn học nước ngoài",
          "description": "Các loại sách Văn học nước ngoài",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/18. sách nông- lâm- _1530209180878.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "8ec5ClIV",
            "name": "Chính trị",
            "description": "Các loại sách Chính trị",
            "parentCategoryId": "w7FPuBSm",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "w7FPuBSm",
              "name": "Sách kiến thức tổng hợp",
              "description": "Các loại sách kiến thức tổng hợp",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "9PsJiPc2",
            "name": "Tôn giáo - Triết học",
            "description": "Các loại sách Tôn giáo - Triết học",
            "parentCategoryId": "w7FPuBSm",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "w7FPuBSm",
              "name": "Sách kiến thức tổng hợp",
              "description": "Các loại sách kiến thức tổng hợp",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "JosMumUd",
            "name": "Ẩm thực - Làm đẹp",
            "description": "Các loại sách Ẩm thực - Làm đẹp",
            "parentCategoryId": "w7FPuBSm",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "w7FPuBSm",
              "name": "Sách kiến thức tổng hợp",
              "description": "Các loại sách kiến thức tổng hợp",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "PGcjfQTm",
            "name": "Sức khoẻ - Y học - Dinh dưỡng",
            "description": "Các loại sách Sức khoẻ - Y học - Dinh dưỡng",
            "parentCategoryId": "w7FPuBSm",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "w7FPuBSm",
              "name": "Sách kiến thức tổng hợp",
              "description": "Các loại sách kiến thức tổng hợp",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "pMHdteck",
            "name": "Địa lý",
            "description": "Các loại sách Địa lý",
            "parentCategoryId": "w7FPuBSm",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "w7FPuBSm",
              "name": "Sách kiến thức tổng hợp",
              "description": "Các loại sách kiến thức tổng hợp",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "ZNTxFLHv",
            "name": "Khoa học phổ thông",
            "description": "Các loại sách Khoa học phổ thông",
            "parentCategoryId": "w7FPuBSm",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "w7FPuBSm",
              "name": "Sách kiến thức tổng hợp",
              "description": "Các loại sách kiến thức tổng hợp",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.701Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.701Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=w7FPuBSm",
        "id": "w7FPuBSm",
        "name": "Sách kiến thức tổng hợp",
        "description": "Các loại sách kiến thức tổng hợp",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/sách tham khảo_1529581210847.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=WehPUxu1",
        "id": "WehPUxu1",
        "name": "Quản trị - Lãnh đạo",
        "description": "Các loại sách Quản trị - Lãnh đạo",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=WNt5cnuw",
        "id": "WNt5cnuw",
        "name": "Du ký - Phóng sự - Ký sự",
        "description": "Các loại sách Du ký - Phóng sự - Ký sự",
        "parentCategoryId": "LqFetlSG",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "LqFetlSG",
          "name": "Văn học Việt Nam",
          "description": "Các loại sách Văn học Việt Nam",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=x2snTQub",
        "id": "x2snTQub",
        "name": "Lịch sử Việt Nam",
        "description": "Các loại sách Lịch sử Việt Nam",
        "parentCategoryId": "7GTGHdsD",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "7GTGHdsD",
          "name": "Sách lịch sử",
          "description": "Các loại sách lịch sử",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=XRSRtJIp",
        "id": "XRSRtJIp",
        "name": "Forbes",
        "description": "Các loại sách Forbes",
        "parentCategoryId": "56HQuvhX",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "56HQuvhX",
          "name": "Tạp chí",
          "description": "Các loại sách Tạp chí",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/9. truyện tranh_1530208917912.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=XviKFrIE",
        "id": "XviKFrIE",
        "name": "Tài chính - Kế toán - Đầu tư",
        "description": "Các loại sách Tài chính - Kế toán - Đầu tư",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=y2hqujUL",
        "id": "y2hqujUL",
        "name": "Kinh tế",
        "description": "Các loại sách Kinh tế",
        "parentCategoryId": "OJhwSVT9",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OJhwSVT9",
          "name": "Sách Tiếng Anh",
          "description": "Các loại sách Tiếng Anh",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=Y6IYC0HD",
        "id": "Y6IYC0HD",
        "name": "Tác phẩm kinh điển",
        "description": "Các loại sách Tác phẩm kinh điển",
        "parentCategoryId": "zytBS6fk",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "zytBS6fk",
          "name": "Văn học nước ngoài",
          "description": "Các loại sách Văn học nước ngoài",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 3,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=y9cqTpul",
        "id": "y9cqTpul",
        "name": "Tư duy - Kỹ năng sống",
        "description": "Các loại sách Tư duy - Kỹ năng sống",
        "parentCategoryId": "4EF6uqUM",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "4EF6uqUM",
          "name": "Sách kỹ năng - sống đẹp",
          "description": "Các loại sách kỹ năng - sống đẹp",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/sách thiếu nhi_1529581149475.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=YDcbIyCA",
        "id": "YDcbIyCA",
        "name": "PR - Truyền thông",
        "description": "Các loại sách PR - Truyền thông",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/5. sách bà mẹ & em b_1530208859712.png",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=yeU9I7u9",
        "id": "yeU9I7u9",
        "name": "Khởi nghiệp",
        "description": "Các loại sách Khởi nghiệp",
        "parentCategoryId": "OVuEcBfb",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "OVuEcBfb",
          "name": "Sách kinh tế",
          "description": "Các loại sách kinh tế",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=yOs2SNHB",
        "id": "yOs2SNHB",
        "name": "Tâm lý - sống đẹp",
        "description": "Các loại sách Tâm lý - sống đẹp",
        "parentCategoryId": "4EF6uqUM",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "4EF6uqUM",
          "name": "Sách kỹ năng - sống đẹp",
          "description": "Các loại sách kỹ năng - sống đẹp",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=zKIkuDhQ",
        "id": "zKIkuDhQ",
        "name": "Thơ - Ca dao - Kịch",
        "description": "Các loại sách Thơ - Ca dao - Kịch",
        "parentCategoryId": "LqFetlSG",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "LqFetlSG",
          "name": "Văn học Việt Nam",
          "description": "Các loại sách Văn học Việt Nam",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.700Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      },
      {
        "urlImage": "",
        "bookCount": 0,
        "subCategories": [],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=ZNTxFLHv",
        "id": "ZNTxFLHv",
        "name": "Khoa học phổ thông",
        "description": "Các loại sách Khoa học phổ thông",
        "parentCategoryId": "w7FPuBSm",
        "subCategoriesId": null,
        "parentCategory": {
          "id": "w7FPuBSm",
          "name": "Sách kiến thức tổng hợp",
          "description": "Các loại sách kiến thức tổng hợp",
          "parentCategoryId": null,
          "subCategoriesId": null,
          "parentCategory": null,
          "createdAt": "2021-01-22T14:03:36.701Z",
          "isDeleted": false
        },
        "createdAt": "2021-01-22T14:03:36.701Z",
        "isDeleted": false
      },
      {
        "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/17. sách chính trị_p_1530209169683.png",
        "bookCount": 0,
        "subCategories": [
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "30cBuVh4",
            "name": "Thơ - Kịch",
            "description": "Các loại sách Thơ - Kịch",
            "parentCategoryId": "zytBS6fk",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "zytBS6fk",
              "name": "Văn học nước ngoài",
              "description": "Các loại sách Văn học nước ngoài",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/19. sách công nghệ_t_1530209194449.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "ALt6iVSE",
            "name": "Kiếm hiệp",
            "description": "Các loại sách Kiếm hiệp",
            "parentCategoryId": "zytBS6fk",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "zytBS6fk",
              "name": "Văn học nước ngoài",
              "description": "Các loại sách Văn học nước ngoài",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/15. sách tôn giáo- t_1530209146790.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "BrF8uQfO",
            "name": "Tự truyện- Hồi ký - Nhân vật",
            "description": "Các loại sách Tự truyện- Hồi ký - Nhân vật",
            "parentCategoryId": "zytBS6fk",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "zytBS6fk",
              "name": "Văn học nước ngoài",
              "description": "Các loại sách Văn học nước ngoài",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "ljh2HAuA",
            "name": "Tiểu thuyết",
            "description": "Các loại sách Tiểu thuyết",
            "parentCategoryId": "zytBS6fk",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "zytBS6fk",
              "name": "Văn học nước ngoài",
              "description": "Các loại sách Văn học nước ngoài",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "https://the-books-dev-files.s3.amazonaws.com/Image/13. sách khoa học- k_1530209114437.png",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "ReCKUNu0",
            "name": "Truyện ngắn - Tản văn",
            "description": "Các loại sách Truyện ngắn - Tản vănt",
            "parentCategoryId": "zytBS6fk",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "zytBS6fk",
              "name": "Văn học nước ngoài",
              "description": "Các loại sách Văn học nước ngoài",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          },
          {
            "urlImage": "",
            "bookCount": 0,
            "subCategories": [],
            "urlCategory": null,
            "id": "Y6IYC0HD",
            "name": "Tác phẩm kinh điển",
            "description": "Các loại sách Tác phẩm kinh điển",
            "parentCategoryId": "zytBS6fk",
            "subCategoriesId": null,
            "parentCategory": {
              "id": "zytBS6fk",
              "name": "Văn học nước ngoài",
              "description": "Các loại sách Văn học nước ngoài",
              "parentCategoryId": null,
              "subCategoriesId": null,
              "parentCategory": null,
              "createdAt": "2021-01-22T14:03:36.700Z",
              "isDeleted": false
            },
            "createdAt": "2021-01-22T14:03:36.700Z",
            "isDeleted": false
          }
        ],
        "urlCategory": "https://the-books-web-staging.enouvo.com/books?=&categoryids=zytBS6fk",
        "id": "zytBS6fk",
        "name": "Văn học nước ngoài",
        "description": "Các loại sách Văn học nước ngoài",
        "parentCategoryId": null,
        "subCategoriesId": null,
        "parentCategory": null,
        "createdAt": "2021-01-22T14:03:36.700Z",
        "isDeleted": false
      }
    ]
  }